env: "dev"

http_server:
  address: "localhost:8082"
  timeout: 5s
  idle_timeout: 30s

db:
  host: "localhost"
  port: "5432"
  sslmode: "disable"

kafka:
  brokers:
    - "localhost:9092"
  topic: "orders"
  group_id: "order_service_group"